name: CD
on:
  push:
    branches:
      - "release/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["14.18.2"]
        mongodb-version: ["latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache modules
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn
      - name: Build website
        run: npm run build
        env:
          REACT_APP_TIINGO_API_KEY: ${{ secrets.REACT_APP_TIINGO_API_KEY }}
          REACT_APP_ALPACA_MARKETS_HOST: ${{ secrets.REACT_APP_ALPACA_MARKETS_HOST }}
          REACT_APP_ALPACA_KEY_ID: ${{ secrets.REACT_APP_ALPACA_KEY_ID }}
          REACT_APP_ALPACA_SECRET_KEY: ${{ secrets.REACT_APP_ALPACA_SECRET_KEY }}
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.CD_GITHUB_TOKEN }}
          publish_dir: ./build
